-- Migration 002: EA configs, subscriptions, and activation codes

BEGIN;

-- EA configuration per user+account
CREATE TABLE IF NOT EXISTS ea_configs (
  id                  BIGSERIAL PRIMARY KEY,
  user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  account_id          BIGINT REFERENCES mt5_accounts(id) ON DELETE SET NULL,
  login               VARCHAR(64) NOT NULL,
  is_running          BOOLEAN NOT NULL DEFAULT FALSE,
  trade_type          VARCHAR(8) NOT NULL DEFAULT 'buy',   -- 'buy' | 'sell'
  symbol1             VARCHAR(32) NOT NULL DEFAULT 'XAUUSD',
  symbol2             VARCHAR(32) NOT NULL DEFAULT 'XAUUSD.',
  initial_lot         REAL NOT NULL DEFAULT 0.1,
  magic_no            INTEGER NOT NULL DEFAULT 12345,
  stop_loss           REAL NOT NULL DEFAULT 0,
  take_profit         REAL NOT NULL DEFAULT 0,
  symbol_to_trade     VARCHAR(8) NOT NULL DEFAULT 'Sym1',   -- 'Sym1' | 'Sym2'
  symbol_to_close     VARCHAR(8) NOT NULL DEFAULT 'Sym1',
  trade_on_same_level BOOLEAN NOT NULL DEFAULT FALSE,
  levels              JSONB NOT NULL DEFAULT '[]',
  -- Array of { diffToTrade: float, diffToCut: float, numPairs: int }
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_ea_user_login UNIQUE (user_id, login)
);

CREATE INDEX IF NOT EXISTS idx_ea_configs_user_id ON ea_configs (user_id);

-- Subscription tiers
CREATE TABLE IF NOT EXISTS subscriptions (
  id              BIGSERIAL PRIMARY KEY,
  user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tier            VARCHAR(16) NOT NULL DEFAULT 'free',  -- 'free' | 'standard' | 'premium'
  expires_at      TIMESTAMPTZ,                          -- NULL = never expires
  activated_by    VARCHAR(32),                          -- 'code' | 'admin'
  activation_code VARCHAR(32),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_subscription_user UNIQUE (user_id)
);

CREATE INDEX IF NOT EXISTS idx_subscriptions_user_id ON subscriptions (user_id);

-- Activation codes (generated by admin)
CREATE TABLE IF NOT EXISTS activation_codes (
  id          BIGSERIAL PRIMARY KEY,
  code        VARCHAR(32) UNIQUE NOT NULL,
  tier        VARCHAR(16) NOT NULL DEFAULT 'standard', -- 'standard' | 'premium'
  duration_days INTEGER NOT NULL DEFAULT 30,
  used_by     BIGINT REFERENCES users(id),
  used_at     TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_activation_codes_code ON activation_codes (code);

COMMIT;
